sudo: false
language: python
python:
    - "2.7"
    - "3.5"
    - "pypy"
    - "pypy3"

install:
    - pip install .

script: py.test

before_install:
      pip install codecov
after_success:
      codecov
